### ISSUE TITLE
Change the title on the GH Page - remove Bootstrap and add an icon

### ISSUE THREAD

**Issue by oliversaal** [oliversaal/TinkerLand#5]
The default site for TinkerLand repo is http://www.digitalarthingy.com. However, it's placeholder site with a long title, "Digital Art Thingy Bootstrap", and no icon. Shorten the title to just "Digital Art Thingy" and add a n icon that represents the site.

**Comment by nicsaal** [comment]
Thanks, is this needed because the website has a DB and can store login info?

**Comment by oliversaal** [comment]
No, the website is just static content. I make this change because it was annoying without it IMO

**Comment by oliversaal** [comment]
Changes were addressed in commit 16c3894599ea9
